# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hdelaunay_K <- function(points, isolations) {
    .Call(`_gyro_hdelaunay_K`, points, isolations)
}

hdelaunay_EK <- function(points, isolations) {
    .Call(`_gyro_hdelaunay_EK`, points, isolations)
}

